# Set the base image for subsequent instructions
ARG BASE_PHP_IMAGE=php:8.2
FROM $BASE_PHP_IMAGE

ARG NODE_VERSION=16

# Update packages
RUN apt-get update \
  && apt-get install -qq git curl libmcrypt-dev libjpeg-dev libpng-dev libfreetype6-dev libbz2-dev libzip-dev zlib1g-dev \
  && curl -sLS https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - \
  && apt-get -y autoremove \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install needed extensions
# Here you can install any other extension that you need during the test and deployment process
RUN docker-php-ext-install pdo_mysql zip

# Install Composer
RUN curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
  && composer global require "laravel/envoy"
